const actionTypes = {
    FETCH_EMPLOYEES_ASYNC: 'FETCH_EMPLOYEES_ASYNC',
    FEATCH_EMPLOYEES_OK: 'FEATCH_EMPLOYEES_OK',
    FEATCH_ROLES_OK: 'FEATCH_ROLES_OK',
    CLICK_EMPLOYEE: 'CLICK_EMPLOYEE',
    CLICK_EMPLOYEE_ASYNC: 'CLICK_EMPLOYEE_ASYNC',
    CLICK_CHANGE_EMPLOYEE_ASYNC: 'CLICK_CHANGE_EMPLOYEE_ASYNC',
    FEATCH_SELECTED_EMPLOYEE_OK: 'FEATCH_SELECTED_EMPLOYEE_OK',
    FEATCH_EMPLOYEE_TOBE_CHANGE_OK: 'FEATCH_EMPLOYEE_TOBE_CHANGE_OK',
    CLICK_PAGENO_ASYNC: 'CLICK_PAGENO_ASYNC',
    CHANGE_PAGE_SIZE: 'CHANGE_PAGE_SIZE',
    CHANGE_PAGE_SIZE_ASYNC: 'CHANGE_PAGE_SIZE_ASYNC',
    FETCH_EMPLOYEE_TOBE_UPDATE_ASYNC: 'FETCH_EMPLOYEE_TOBE_UPDATE_ASYNC',
    UPDATE_EMPLOYEE_ASYNC: 'UPDATE_EMPLOYEE_ASYNC',
    FETCH_EMPLOYEE_FOR_DISPLAY_ASYNC: 'FETCH_EMPLOYEE_FOR_DISPLAY_ASYNC',
    FEATCH_EMPLOYEE_FOR_DISPLAY_OK: 'FEATCH_EMPLOYEE_FOR_DISPLAY_OK',
    CREATE_EMPLOYEE_FETCH_ROLES_ASYNC: 'CREATE_EMPLOYEE_FETCH_ROLES_ASYNC',
    CREATE_EMPLOYEE_ASYNC: 'CREATE_EMPLOYEE_ASYNC',
    ON_CLICK_DELETE_EMPLOYEE_ASYNC: 'ON_CLICK_DELETE_EMPLOYEE_ASYNC',
    CHANGE_FILTER_ASYNC: 'CHANGE_FILTER_ASYNC',
    CHANGE_FILTER: 'CHANGE_FILTER'
}
  
export default actionTypes